from typing import Dict, Any

def export_report_to_txt(file_path: str, results: Dict[str, Any], explanation: Dict[str, str], target_col: str, sensitive_col: str, selected_columns: list):
    """
    Exports the bias analysis results to a cleanly structured .txt file.
    """
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write("=========================================================\n")
        f.write("               FAIRSIGHT AI - BIAS REPORT\n")
        f.write("=========================================================\n\n")
        
        f.write("--- ANALYSIS CONFIGURATION ---\n")
        f.write(f"Target Column (Outcome): {target_col}\n")
        f.write(f"Sensitive Attribute: {sensitive_col}\n")
        f.write(f"Dataset Columns: {', '.join(selected_columns)}\n\n")
        
        f.write("--- BIAS METRICS ---\n")
        f.write(f"Risk Level: {results.get('risk_level', 'Unknown')}\n")
        f.write(f"Bias Score: {results['bias_score']:.3f}\n")
        f.write(f"Disparate Impact: {results['disparate_impact']:.3f}\n\n")
        
        f.write("--- GROUP MEANS ---\n")
        for group, mean_val in results['group_means'].items():
            f.write(f"  - {group}: {mean_val:.3f}\n")
        f.write("\n")
        
        f.write("--- SUMMARY ---\n")
        # Strip HTML tags for TXT format
        summary_text = explanation['summary'].replace('<b>', '').replace('</b>', '')
        f.write(f"{summary_text}\n\n")
        
        f.write("--- WHY THIS MATTERS ---\n")
        f.write(f"{explanation['why_it_matters']}\n\n")
        
        f.write("--- SUGGESTED ACTIONS ---\n")
        actions_text = explanation['actions'].replace('<ul>', '').replace('</ul>', '')
        actions_text = actions_text.replace('<li>', '  - ').replace('</li>', '\n')
        f.write(f"{actions_text.strip()}\n")
        
        f.write("\n=========================================================\n")
        f.write("Generated by FairSight AI\n")
        f.write("=========================================================\n")
